### ISSUE TITLE
質問の質問の解答の解答 

### ISSUE THREAD

**Issue by RamuneRemonedo** [Akkey735/Akkey735#1]
Scalaは静的に型付けされたプログラミング言語だけど、Java はマルチプラットフォームのネットワーク中心のプログラミング言語
Scalaは最新の同時実行をサポートするためにアクター モデルを使用するけど、Java は従来のスレッドベースのモデルを同時実行に使用
Scalaの変数はデフォルトで不変型だけど、Java 変数はデフォルトで可変型
Scalaは遅延評価をサポートしてるけど、Java は遅延評価をサポートしてない
Scalaに静的メンバーが含まれてないけど、Java には静的メンバーが含まれてる。
Scalaは演算子のオーバーロードをサポートしてるけど、Java は演算子のオーバーロードをサポートしてない
Scalaは下位互換性を提供、Java は下位互換性を提供
コードがネストされてるから、Scala は読みにくい、Java は読みやすいぞ
Scalaフレームワークは Play、Lift だけど、Java フレームワークは Spring、Grails などなど

**Comment by RamuneRemonedo** [comment]
m(__)m

**Comment by RamuneRemonedo** [comment]
あのブロック解除をお願いします

**Comment by Akkey735** [comment]
別に求めてないっす、scalaは。

**Comment by RamuneRemonedo** [comment]
フレ送って;;

**Comment by Akkey735** [comment]
俺...docker触れたよ！！！
...それだけっす。
